param(
  [int]$AppPort = 18080,
  [int]$MockPort = 19090,
  [string]$DataDir = ""
)

$ErrorActionPreference = "Stop"

function Invoke-Native {
  param(
    [string]$FilePath,
    [string[]]$ArgumentList
  )

  & $FilePath @ArgumentList
  if ($LASTEXITCODE -ne 0) {
    throw "$FilePath $($ArgumentList -join ' ') failed with exit code $LASTEXITCODE"
  }
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
if ($DataDir -eq "") {
  $DataDir = Join-Path $RepoRoot "tmp\browser-mock"
}
$DataDir = [System.IO.Path]::GetFullPath($DataDir)
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
$ConfigPath = Join-Path $DataDir "config.yml"

$MockURL = "http://127.0.0.1:$MockPort"
$AppURL = "http://127.0.0.1:$AppPort"

$config = @"
---
title: "Collector mock dashboard"
subtitle: "homer-go browser preview"
logo: "/assets/icons/homer-go-logo-v2.png"
header: true
footer: '<p>Collector data is served from local test fixtures.</p>'
columns: "3"
connectivityCheck: false
updateIntervalMs: 5000
defaults:
  layout: columns
  colorTheme: auto
theme: default
message:
  style: "is-info"
  title: "Browser mock"
  content: "All collector cards below use fixture-backed mock responses."
links:
  - name: "Mock API"
    icon: "fas fa-server"
    url: "$MockURL/ping"
services:
  - name: "Status and monitoring"
    icon: "fas fa-heart-pulse"
    items:
      - name: "Ping"
        type: "Ping"
        icon: "fas fa-heart-pulse"
        url: "$MockURL/ping"
      - name: "AdGuard Home"
        type: "AdGuardHome"
        icon: "fas fa-shield-halved"
        url: "#"
        endpoint: "$MockURL/adguardhome"
        username: "adguard"
        password: "secret"
      - name: "Gatus"
        type: "Gatus"
        icon: "fas fa-chart-line"
        url: "#"
        endpoint: "$MockURL/gatus"
        groups:
          - "Services"
      - name: "Healthchecks"
        type: "Healthchecks"
        icon: "fas fa-check-double"
        url: "#"
        endpoint: "$MockURL/healthchecks"
        apikey: "health-token"
      - name: "Prometheus"
        type: "Prometheus"
        icon: "fas fa-fire"
        url: "#"
        endpoint: "$MockURL/prometheus"
  - name: "Apps"
    icon: "fas fa-layer-group"
    items:
      - name: "Gotify"
        type: "Gotify"
        icon: "fas fa-bell"
        url: "#"
        endpoint: "$MockURL/gotify"
        apikey: "token"
      - name: "Immich"
        type: "Immich"
        icon: "fas fa-images"
        url: "#"
        endpoint: "$MockURL/immich"
        apikey: "immich-token"
      - name: "Mealie"
        type: "Mealie"
        icon: "fas fa-utensils"
        url: "#"
        endpoint: "$MockURL/mealie"
        apikey: "mealie-token"
      - name: "Miniflux"
        type: "Miniflux"
        icon: "fas fa-rss"
        url: "#"
        endpoint: "$MockURL/miniflux"
        apikey: "mini-token"
      - name: "Nextcloud"
        type: "Nextcloud"
        icon: "fas fa-cloud"
        url: "#"
        endpoint: "$MockURL/nextcloud"
      - name: "Paperless NG"
        type: "PaperlessNG"
        icon: "fas fa-file-lines"
        url: "#"
        endpoint: "$MockURL/paperlessng"
        apikey: "paper-token"
  - name: "Media and downloads"
    icon: "fas fa-film"
    items:
      - name: "Jellyfin"
        type: "Jellyfin"
        icon: "fas fa-play"
        url: "#"
        endpoint: "$MockURL/jellyfin"
        apikey: "jelly-token"
      - name: "Medusa"
        type: "Medusa"
        icon: "fas fa-tv"
        url: "#"
        endpoint: "$MockURL/medusa"
        apikey: "medusa-token"
      - name: "Mylar"
        type: "Mylar"
        icon: "fas fa-book-open"
        url: "#"
        endpoint: "$MockURL/mylar"
        apikey: "mylar-token"
      - name: "Prowlarr"
        type: "Prowlarr"
        icon: "fas fa-magnifying-glass"
        url: "#"
        endpoint: "$MockURL/prowlarr"
        apikey: "prowl-token"
      - name: "Tautulli"
        type: "Tautulli"
        icon: "fas fa-chart-simple"
        url: "#"
        endpoint: "$MockURL/tautulli"
        apikey: "tautulli-token"
      - name: "Emby"
        type: "Emby"
        icon: "fas fa-film"
        url: "#"
        endpoint: "$MockURL/emby"
        apikey: "emby-token"
        libraryType: "series"
      - name: "SABnzbd"
        type: "SABnzbd"
        icon: "fas fa-download"
        url: "#"
        endpoint: "$MockURL/sabnzbd"
        apikey: "sab-token"
      - name: "qBittorrent"
        type: "qBittorrent"
        icon: "fas fa-magnet"
        url: "#"
        endpoint: "$MockURL/qbittorrent"
      - name: "Tdarr"
        type: "Tdarr"
        icon: "fas fa-clapperboard"
        url: "#"
        endpoint: "$MockURL/tdarr"
        apikey: "tdarr-token"
  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - name: "Docker Socket Proxy"
        type: "DockerSocketProxy"
        icon: "fab fa-docker"
        url: "#"
        endpoint: "$MockURL/dockersocketproxy"
      - name: "PeaNUT"
        type: "PeaNUT"
        icon: "fas fa-plug"
        url: "#"
        endpoint: "$MockURL/peanut"
        device: "ups"
      - name: "PiAlert"
        type: "PiAlert"
        icon: "fas fa-network-wired"
        url: "#"
        endpoint: "$MockURL/pialert"
      - name: "NetAlertX"
        type: "NetAlertx"
        icon: "fas fa-wifi"
        url: "#"
        endpoint: "$MockURL/netalertx"
        apikey: "net-token"
      - name: "Scrutiny"
        type: "Scrutiny"
        icon: "fas fa-hard-drive"
        url: "#"
        endpoint: "$MockURL/scrutiny"
      - name: "Speedtest Tracker"
        type: "SpeedtestTracker"
        icon: "fas fa-gauge-high"
        url: "#"
        endpoint: "$MockURL/speedtesttracker"
        apikey: "speed-token"
      - name: "WUD"
        type: "WUD"
        icon: "fas fa-boxes-stacked"
        url: "#"
        endpoint: "$MockURL/wud"
      - name: "Glances"
        type: "Glances"
        icon: "fas fa-microchip"
        url: "#"
        endpoint: "$MockURL/glances"
      - name: "Home Assistant"
        type: "HomeAssistant"
        icon: "fas fa-house"
        url: "#"
        endpoint: "$MockURL/homeassistant"
        apikey: "ha-token"
        items:
          - "name"
          - "version"
          - "entities"
        separator: " | "
      - name: "HyperHDR"
        type: "HyperHDR"
        icon: "fas fa-lightbulb"
        url: "#"
        endpoint: "$MockURL/hyperhdr"
      - name: "OpenHAB"
        type: "OpenHAB"
        icon: "fas fa-toggle-on"
        url: "#"
        endpoint: "$MockURL/openhab"
        apikey: "ohab-token"
        things: true
        items: true
      - name: "Portainer"
        type: "Portainer"
        icon: "fab fa-docker"
        url: "#"
        endpoint: "$MockURL/portainer"
        apikey: "port-token"
      - name: "Proxmox"
        type: "Proxmox"
        icon: "fas fa-server"
        url: "#"
        endpoint: "$MockURL/proxmox"
        api_token: "PVEAPIToken=root@pam!homer=secret"
        node: "node1"
  - name: "Feeds and arr"
    icon: "fas fa-rss"
    items:
      - name: "FreshRSS"
        type: "FreshRSS"
        icon: "fas fa-rss"
        url: "#"
        endpoint: "$MockURL/freshrss"
        username: "user"
        password: "pass"
      - name: "Lidarr"
        type: "Lidarr"
        icon: "fas fa-music"
        url: "#"
        endpoint: "$MockURL/lidarr"
        apikey: "arr-token"
      - name: "Readarr"
        type: "Readarr"
        icon: "fas fa-book"
        url: "#"
        endpoint: "$MockURL/readarr"
        apikey: "arr-token"
      - name: "Sonarr"
        type: "Sonarr"
        icon: "fas fa-tv"
        url: "#"
        endpoint: "$MockURL/sonarr"
        apikey: "arr-token"
      - name: "Radarr"
        type: "Radarr"
        icon: "fas fa-video"
        url: "#"
        endpoint: "$MockURL/radarr"
        apikey: "arr-token"
      - name: "Uptime Kuma"
        type: "UptimeKuma"
        icon: "fas fa-heart-pulse"
        url: "#"
        endpoint: "$MockURL/uptimekuma"
  - name: "Versions"
    icon: "fas fa-code-branch"
    items:
      - name: "Docuseal"
        type: "Docuseal"
        icon: "fas fa-signature"
        url: "#"
        endpoint: "$MockURL/docuseal"
      - name: "Gitea"
        type: "Gitea"
        icon: "fab fa-git-alt"
        url: "#"
        endpoint: "$MockURL/gitea"
      - name: "Matrix"
        type: "Matrix"
        icon: "fas fa-comments"
        url: "#"
        endpoint: "$MockURL/matrix"
      - name: "Olivetin"
        type: "Olivetin"
        icon: "fas fa-terminal"
        url: "#"
        endpoint: "$MockURL/olivetin"
      - name: "Traefik"
        type: "Traefik"
        icon: "fas fa-route"
        url: "#"
        endpoint: "$MockURL/traefik"
        basic_auth: "user:pass"
      - name: "TrueNAS Scale"
        type: "TruenasScale"
        icon: "fas fa-database"
        url: "#"
        endpoint: "$MockURL/truenasscale"
        api_token: "truenas-token"
      - name: "Vaultwarden"
        type: "Vaultwarden"
        icon: "fas fa-lock"
        url: "#"
        endpoint: "$MockURL/vaultwarden"
      - name: "Wallabag"
        type: "Wallabag"
        icon: "fas fa-bookmark"
        url: "#"
        endpoint: "$MockURL/wallabag"
"@

Set-Content -Encoding UTF8 -Path $ConfigPath -Value $config

$mockExe = Join-Path $DataDir "browser-mock-api.exe"
$appExe = Join-Path $DataDir "homer-go-browser-mock.exe"
$mockOutLog = Join-Path $DataDir "browser-mock-api.out.log"
$mockErrLog = Join-Path $DataDir "browser-mock-api.err.log"
$appOutLog = Join-Path $DataDir "browser-mock-app.out.log"
$appErrLog = Join-Path $DataDir "browser-mock-app.err.log"

Write-Host "Building preview binaries..."
Push-Location $RepoRoot
try {
  Invoke-Native "go" @("build", "-o", $mockExe, "./cmd/browser-mock")
  Invoke-Native "go" @("build", "-o", $appExe, ".")

  Write-Host "Config: $ConfigPath"
  Write-Host "Mock API: $MockURL"
  Write-Host "Dashboard: $AppURL"
  Write-Host "Logs: $mockOutLog, $mockErrLog, $appOutLog, $appErrLog"
  Write-Host "Press Ctrl+C to stop."

  $mock = Start-Process -FilePath $mockExe -ArgumentList @("-addr", "127.0.0.1:$MockPort") -WorkingDirectory $RepoRoot -NoNewWindow -PassThru -RedirectStandardOutput $mockOutLog -RedirectStandardError $mockErrLog
  $app = Start-Process -FilePath $appExe -ArgumentList @("-addr", "127.0.0.1:$AppPort", "-data", $DataDir) -WorkingDirectory $RepoRoot -NoNewWindow -PassThru -RedirectStandardOutput $appOutLog -RedirectStandardError $appErrLog

  while (-not $mock.HasExited -and -not $app.HasExited) {
    Start-Sleep -Milliseconds 500
  }
} finally {
  foreach ($process in @($mock, $app)) {
    if ($null -ne $process -and -not $process.HasExited) {
      Stop-Process -Id $process.Id -Force
    }
  }
  Pop-Location
}
